### ISSUE TITLE
Mixin config plugin triggers re-entrant game class loads

### ISSUE THREAD

**Issue by zml2008** [FrozenBlock/WilderWild#289]
**Description of the Bug Encountered**

Wilder Wild's Mixin config plugin triggers classloads of other game classes. Because this happens during the prepare phase, it causes classes to be loaded with some transformations not applied.

This was originally discovered through an issue in `better-fabric-console`: https://github.com/jpenilla/better-fabric-console/issues/27#issuecomment-1676430768

**Steps To Reproduce**
1. Install wilder wild
2. Install some other mod with a mixin targeting `n.m.n.c.Component`, such as `adventure-platform-fabric` (here included via `better-fabric-console`
3. launch server
4. perform some method that depends on the transformation to `Component` being properly applied

**Expected Behavior**

Game loads without issues, Mixins to `Component` are applied

**Screenshots**

See upstream issue for history, summary:

![debugger outpu](https://user-images.githubusercontent.com/629092/260320690-d576b500-9738-4cdd-b592-aaf6d5c6bbf8.png)

**Logs**

Because of the silent Mixin application failure, you get issues like:
```
[11:17:55 ERROR] [Server thread]: [MinecraftServer] Encountered an unexpected exception
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
        at net.minecraft.server.dedicated.DedicatedServer.sendSystemMessage(DedicatedServer.java:681) ~[?:?]
        at net.minecraft.commands.CommandSourceStack.sendSuccess(CommandSourceStack.java:323) ~[?:?]
        at net.minecraft.server.commands.StopCommand.lambda$register$2(StopCommand.java:16) ~[?:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.1.8.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:287) ~[?:?]
        at net.minecraft.commands.Commands.performPrefixedCommand(Commands.java:280) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:299) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:284) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:671) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Additional context**

This can probably be pretty easily resolved by splitting the values controlling Mixin application into a separate class with nothing but those fields, and no references to non-loader game classes.

**Comment by AViewFromTheTop** [comment]
I have to admit, I’m not entirely understanding this (maybe @Treetrain1 will though)
Would you be able to provide an example of your solution through a couple screenshots?

**Comment by zml2008** [comment]
<img width="846" alt="image" src="https://github.com/FrozenBlock/WilderWild/assets/629092/06721333-5b64-43a0-88b7-cd967cc63d60">

These three references are what cause a problem -- if these fields are moved from `WilderSharedConstants` to their own class file, then this issue should be resolved.

**Comment by AViewFromTheTop** [comment]
> <img alt="image" width="846" src="https://user-images.githubusercontent.com/629092/260323956-06721333-5b64-43a0-88b7-cd967cc63d60.png">
> These three references are what cause a problem -- if these fields are moved from `WilderSharedConstants` to their own class file, then this issue should be resolved.

Ah.
I have to be honest I’m still not sure *why* that causes issues (is WilderSharedConstants loading other classes at the wrong time due to this?) but once I’m home I’ll go fix it.
Thank you so much for letting me know!!

**Comment by zml2008** [comment]
That's the impression the debugger stacktrace gave me -- by loading WilderSharedConstants which has methods which take `Component` arguments, I guess the JVM is loading the `Component` class itself.

Honestly I was surprised when I saw that -- I'd normally think what you did would be fine, but I guess the JVM is more aggressive with linking classes than I thought.

**Comment by AViewFromTheTop** [comment]
> That's the impression the debugger stacktrace gave me -- by loading WilderSharedConstants which has methods which take `Component` arguments, I guess the JVM is loading the `Component` class itself.
> 
> Honestly I was surprised when I saw that -- I'd normally think what you did would be fine, but I guess the JVM is more aggressive with linking classes than I thought.

Yeeeeaaah that stuff’s very convoluted…
It’s been a mixed bag for me with these sorts of things, honestly. Depending on something completely unrelated, sometimes it’ll load every single class that’s imported, or it won’t even touch it unless the method’s called. It’s caused countless issues with client-sides classes for me before, sometimes it works and other times it crashes hard.
No clue what that’s about, but at least there’s an easy way around it with making another class.

**Comment by AViewFromTheTop** [comment]
fixed in the next update

**Comment by sakurawald** [comment]
Hello, it seems there is another conflicts between

```
Wilder Wild v2.4.8 mc1.21
net.kyori:adventure-text-minimessage 4.17.0
net.kyori:adventure-platform-fabric=5.14.0
```

The code
```
player.sendPlayerListHeaderAndFooter(header, footer);
```

will cause 
```
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component net.minecraft.class_2561.asComponent()'
```
